namespace: nokia
name: sros
version: 1.6.0
readme: README.md
authors:
- Sven Wisotzky <sven.wisotzky@nokia.com>
description: Ansible collection to support networking devices running Nokia SR OS
license: BSD-3-Clause
tags:
- collection
- network
- networking
- backup
- mpls
- nokia
- sros
- timos
- netconf
- cli
- cliconf
- terminal
- ansible

repository: http://github.com/nokia/ansible-networking-collections/blob/master/sros
documentation: http://github.com/nokia/ansible-networking-collections/blob/master/sros
homepage: http://github.com/nokia/ansible-networking-collections/blob/master/sros
issues: http://github.com/nokia/ansible-networking-collections/issues
